package br.com.seucaio.githubreposkotlin.core.stub


import br.com.seucaio.githubreposkotlin.data.model.*
import br.com.seucaio.githubreposkotlin.domain.entity.License
import br.com.seucaio.githubreposkotlin.domain.entity.Owner
import br.com.seucaio.githubreposkotlin.domain.entity.Repositories
import br.com.seucaio.githubreposkotlin.domain.entity.Repository

object RepositoryStub {
    object Response {
        val license = LicenseResponse(
            key = "apache-2.0",
            name = "Apache License 2.0",
            spdxId = "Apache-2.0",
            url = "https://api.github.com/licenses/apache-2.0",
            nodeId = "MDc6TGljZW5zZTI=",
        )

        val owner = OwnerResponse(
            login = "square",
            id = 82592,
            nodeId = "MDEyOk9yZ2FuaXphdGlvbjgyNTky",
            avatarUrl = "https://avatars.githubusercontent.com/u/82592?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/square",
            htmlUrl = "https://github.com/square",
            followersUrl = "https://api.github.com/users/square/followers",
            followingUrl = "https://api.github.com/users/square/following{/other_user}",
            gistsUrl = "https://api.github.com/users/square/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/square/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/square/subscriptions",
            organizationsUrl = "https://api.github.com/users/square/orgs",
            reposUrl = "https://api.github.com/users/square/repos",
            eventsUrl = "https://api.github.com/users/square/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/square/received_events",
            type = "Organization",
            siteAdmin = false,
        )

        val repository = RepositoryResponse(
            id = 5152285,
            nodeId = "MDEwOlJlcG9zaXRvcnk1MTUyMjg1",
            name = "okhttp",
            fullName = "square/okhttp",
            isPrivate = false,
            owner = owner,
            htmlUrl = "https://github.com/square/okhttp",
            description = "Square’s meticulous HTTP client for the JVM, Android, and GraalVM.",
            fork = false,
            url = "https://api.github.com/repos/square/okhttp",
            forksUrl = "https://api.github.com/repos/square/okhttp/forks",
            keysUrl = "https://api.github.com/repos/square/okhttp/keys{/key_id}",
            collaboratorsUrl = "https://api.github.com/repos/square/okhttp/collaborators{/collaborator}",
            teamsUrl = "https://api.github.com/repos/square/okhttp/teams",
            hooksUrl = "https://api.github.com/repos/square/okhttp/hooks",
            issueEventsUrl = "https://api.github.com/repos/square/okhttp/issues/events{/number}",
            eventsUrl = "https://api.github.com/repos/square/okhttp/events",
            assigneesUrl = "https://api.github.com/repos/square/okhttp/assignees{/user}",
            branchesUrl = "https://api.github.com/repos/square/okhttp/branches{/branch}",
            tagsUrl = "https://api.github.com/repos/square/okhttp/tags",
            blobsUrl = "https://api.github.com/repos/square/okhttp/git/blobs{/sha}",
            gitTagsUrl = "https://api.github.com/repos/square/okhttp/git/tags{/sha}",
            gitRefsUrl = "https://api.github.com/repos/square/okhttp/git/refs{/sha}",
            treesUrl = "https://api.github.com/repos/square/okhttp/git/trees{/sha}",
            statusesUrl = "https://api.github.com/repos/square/okhttp/statuses/{sha}",
            languagesUrl = "https://api.github.com/repos/square/okhttp/languages",
            stargazersUrl = "https://api.github.com/repos/square/okhttp/stargazers",
            contributorsUrl = "https://api.github.com/repos/square/okhttp/contributors",
            subscribersUrl = "https://api.github.com/repos/square/okhttp/subscribers",
            subscriptionUrl = "https://api.github.com/repos/square/okhttp/subscription",
            commitsUrl = "https://api.github.com/repos/square/okhttp/commits{/sha}",
            gitCommitsUrl = "https://api.github.com/repos/square/okhttp/git/commits{/sha}",
            commentsUrl = "https://api.github.com/repos/square/okhttp/comments{/number}",
            issueCommentUrl = "https://api.github.com/repos/square/okhttp/issues/comments{/number}",
            contentsUrl = "https://api.github.com/repos/square/okhttp/contents/{+path}",
            compareUrl = "https://api.github.com/repos/square/okhttp/compare/{base}...{head}",
            mergesUrl = "https://api.github.com/repos/square/okhttp/merges",
            archiveUrl = "https://api.github.com/repos/square/okhttp/{archive_format}{/ref}",
            downloadsUrl = "https://api.github.com/repos/square/okhttp/downloads",
            issuesUrl = "https://api.github.com/repos/square/okhttp/issues{/number}",
            pullsUrl = "https://api.github.com/repos/square/okhttp/pulls{/number}",
            milestonesUrl = "https://api.github.com/repos/square/okhttp/milestones{/number}",
            notificationsUrl = "https://api.github.com/repos/square/okhttp/notifications{?since,all,participating}",
            labelsUrl = "https://api.github.com/repos/square/okhttp/labels{/name}",
            releasesUrl = "https://api.github.com/repos/square/okhttp/releases{/id}",
            deploymentsUrl = "https://api.github.com/repos/square/okhttp/deployments",
            createdAt = "2012-07-23T13:42:55Z",
            updatedAt = "2022-03-05T15:18:23Z",
            pushedAt = "2022-03-05T16:09:35Z",
            gitUrl = "git://github.com/square/okhttp.git",
            sshUrl = "git@github.com:square/okhttp.git",
            cloneUrl = "https://github.com/square/okhttp.git",
            svnUrl = "https://github.com/square/okhttp",
            homepage = "https://square.github.io/okhttp/",
            size = 46054,
            stargazersCount = 41700,
            watchersCount = 41700,
            language = "Kotlin",
            hasIssues = true,
            hasProjects = false,
            hasDownloads = true,
            hasWiki = false,
            hasPages = true,
            forksCount = 8792,
            mirrorUrl = null,
            archived = false,
            disabled = false,
            openIssuesCount = 128,
            license = license,
            allowForking = true,
            isTemplate = false,
            topics = listOf("android", "graalvm", "java", "kotlin"),
            visibility = "public",
            forks = 8792,
            openIssues = 128,
            watchers = 41700,
            defaultBranch = "master",
            score = 1.0,
        )

        val repositories = RepositoriesResponse(
            totalCount = 758480,
            incompleteResults = false,
            items = listOf(repository)
        )

        val repositoriesError = ApiErrorResponseResponse(
            message = "",
            errors = listOf(
                ApiErrorResponseResponse.ErrorResponse(
                    resource = "Search",
                    field = "q",
                    code = "missing"
                )
            ),
            documentationUrl = "https://docs.github.com/v3/search"
        )

    }

    object Model {
        val license = License(
            key = "apache-2.0",
            name = "Apache License 2.0",
            spdxId = "Apache-2.0",
            url = "https://api.github.com/licenses/apache-2.0",
            nodeId = "MDc6TGljZW5zZTI=",
        )

        val owner = Owner(
            login = "square",
            id = 82592,
            nodeId = "MDEyOk9yZ2FuaXphdGlvbjgyNTky",
            avatarUrl = "https://avatars.githubusercontent.com/u/82592?v=4",
            gravatarId = "",
            url = "https://api.github.com/users/square",
            htmlUrl = "https://github.com/square",
            followersUrl = "https://api.github.com/users/square/followers",
            followingUrl = "https://api.github.com/users/square/following{/other_user}",
            gistsUrl = "https://api.github.com/users/square/gists{/gist_id}",
            starredUrl = "https://api.github.com/users/square/starred{/owner}{/repo}",
            subscriptionsUrl = "https://api.github.com/users/square/subscriptions",
            organizationsUrl = "https://api.github.com/users/square/orgs",
            reposUrl = "https://api.github.com/users/square/repos",
            eventsUrl = "https://api.github.com/users/square/events{/privacy}",
            receivedEventsUrl = "https://api.github.com/users/square/received_events",
            type = "Organization",
            siteAdmin = false,
        )

        val repository = Repository(
            id = 5152285,
            nodeId = "MDEwOlJlcG9zaXRvcnk1MTUyMjg1",
            name = "okhttp",
            fullName = "square/okhttp",
            isPrivate = false,
            owner = owner,
            htmlUrl = "https://github.com/square/okhttp",
            description = "Square’s meticulous HTTP client for the JVM, Android, and GraalVM.",
            fork = false,
            url = "https://api.github.com/repos/square/okhttp",
            forksUrl = "https://api.github.com/repos/square/okhttp/forks",
            keysUrl = "https://api.github.com/repos/square/okhttp/keys{/key_id}",
            collaboratorsUrl = "https://api.github.com/repos/square/okhttp/collaborators{/collaborator}",
            teamsUrl = "https://api.github.com/repos/square/okhttp/teams",
            hooksUrl = "https://api.github.com/repos/square/okhttp/hooks",
            issueEventsUrl = "https://api.github.com/repos/square/okhttp/issues/events{/number}",
            eventsUrl = "https://api.github.com/repos/square/okhttp/events",
            assigneesUrl = "https://api.github.com/repos/square/okhttp/assignees{/user}",
            branchesUrl = "https://api.github.com/repos/square/okhttp/branches{/branch}",
            tagsUrl = "https://api.github.com/repos/square/okhttp/tags",
            blobsUrl = "https://api.github.com/repos/square/okhttp/git/blobs{/sha}",
            gitTagsUrl = "https://api.github.com/repos/square/okhttp/git/tags{/sha}",
            gitRefsUrl = "https://api.github.com/repos/square/okhttp/git/refs{/sha}",
            treesUrl = "https://api.github.com/repos/square/okhttp/git/trees{/sha}",
            statusesUrl = "https://api.github.com/repos/square/okhttp/statuses/{sha}",
            languagesUrl = "https://api.github.com/repos/square/okhttp/languages",
            stargazersUrl = "https://api.github.com/repos/square/okhttp/stargazers",
            contributorsUrl = "https://api.github.com/repos/square/okhttp/contributors",
            subscribersUrl = "https://api.github.com/repos/square/okhttp/subscribers",
            subscriptionUrl = "https://api.github.com/repos/square/okhttp/subscription",
            commitsUrl = "https://api.github.com/repos/square/okhttp/commits{/sha}",
            gitCommitsUrl = "https://api.github.com/repos/square/okhttp/git/commits{/sha}",
            commentsUrl = "https://api.github.com/repos/square/okhttp/comments{/number}",
            issueCommentUrl = "https://api.github.com/repos/square/okhttp/issues/comments{/number}",
            contentsUrl = "https://api.github.com/repos/square/okhttp/contents/{+path}",
            compareUrl = "https://api.github.com/repos/square/okhttp/compare/{base}...{head}",
            mergesUrl = "https://api.github.com/repos/square/okhttp/merges",
            archiveUrl = "https://api.github.com/repos/square/okhttp/{archive_format}{/ref}",
            downloadsUrl = "https://api.github.com/repos/square/okhttp/downloads",
            issuesUrl = "https://api.github.com/repos/square/okhttp/issues{/number}",
            pullsUrl = "https://api.github.com/repos/square/okhttp/pulls{/number}",
            milestonesUrl = "https://api.github.com/repos/square/okhttp/milestones{/number}",
            notificationsUrl = "https://api.github.com/repos/square/okhttp/notifications{?since,all,participating}",
            labelsUrl = "https://api.github.com/repos/square/okhttp/labels{/name}",
            releasesUrl = "https://api.github.com/repos/square/okhttp/releases{/id}",
            deploymentsUrl = "https://api.github.com/repos/square/okhttp/deployments",
            createdAt = "2012-07-23T13:42:55Z",
            updatedAt = "2022-03-05T15:18:23Z",
            pushedAt = "2022-03-05T16:09:35Z",
            gitUrl = "git://github.com/square/okhttp.git",
            sshUrl = "git@github.com:square/okhttp.git",
            cloneUrl = "https://github.com/square/okhttp.git",
            svnUrl = "https://github.com/square/okhttp",
            homepage = "https://square.github.io/okhttp/",
            size = 46054,
            stargazersCount = 41700,
            watchersCount = 41700,
            language = "Kotlin",
            hasIssues = true,
            hasProjects = false,
            hasDownloads = true,
            hasWiki = false,
            hasPages = true,
            forksCount = 8792,
            mirrorUrl = null,
            archived = false,
            disabled = false,
            openIssuesCount = 128,
            license = license,
            allowForking = true,
            isTemplate = false,
            topics = listOf("android", "graalvm", "java", "kotlin"),
            visibility = "public",
            forks = 8792,
            openIssues = 128,
            watchers = 41700,
            defaultBranch = "master",
            score = 1.0,
        )

        val repositories = Repositories(
            totalCount = 758480,
            incompleteResults = false,
            items = listOf(repository)
        )
    }

}